/*
 *                This file is part of Laserinne.
 * 
 *  Laser projections in public space, inspiration and
 *  information, exploring the aesthetic and interactive possibilities of
 *  laser-based displays.
 * 
 *  http://www.laserinne.com/
 * 
 * Laserinne is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Laserinne is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Laserinne. If not, see <http://www.gnu.org/licenses/>.
 */

package com.laserinne.util;

import geomerative.RFont;
import laserschein.Laser3D;
import laserschein.Laserschein;
import processing.core.PApplet;

/**
 * Abstract superclass for Laserinne sketches.
 * 
 * You are supposed to extend this to get some of the ready made functionality
 * for sketches made to Levi.
 * 
 * Remember: When you've overridden a method you almost always want to call the
 * superclass method as the first call in your method! This gives you the
 * benefits of having the functionality that's already there in your sketch as
 * well.
 * 
 * @author Jyrki Lilja
 */

public abstract class LaserinneSketch extends PApplet {
    /**
     * Generated by Jyrki Lilja on 2011-09-27 11.38
     */
    private static final long serialVersionUID = 5151648775184165402L;
    
    /**
     * Holds an instance of Laserschein.
     */
    protected Laserschein laser;
    /**
     * Holds an instance of the laser renderer.
     */
    protected Laser3D laserRenderer;
    
    /**
     * Tracking gives us all skiers in the slope.
     */
    protected Tracking tracking;
    
    /**
     * RFont used for displaying both the FPS (on screen) and the winner
     * (on laser).
     */
    protected RFont font;
    
    /**
     * Sketch width and height.
     */
    protected static final int WIDTH = 640;
    protected static final int HEIGHT = 480;
    
    /**
     * Laser color: ARGB(FF, 00, FF, 00) means full intensity green.
     */
    public static final int LASER_COLOR = 0xFFFF0000;
    /**
     * Screen color: ARGB(FF, 00, 00, FF) means full intensity blue.
     */
    public static final int SCREEN_COLOR = 0xFF0000FF;

    /**
     * Laser scan speed used when displaying text.
     */
    public static final int TEXT_SCANSPEED = 60000;
    
    public void setup() {
        size(TwoPlayerCompetition.WIDTH, TwoPlayerCompetition.HEIGHT, processing.opengl.PGraphicsOpenGL.OPENGL);
        frameRate(-1); // Use maximum frame rate.
        
        /*
         * Initialize laserschein for use with EasyLaseUSB2.
         */
        laser = new Laserschein(this, Laserschein.EASYLASEUSB2);
        laserRenderer = laser.renderer();
        
        /*
         * Set Skier class ready for use.
         */
        Skier.width(LaserinneSketch.WIDTH);
        Skier.height(LaserinneSketch.HEIGHT);
        
        /*
         * Initialize RG and font.
         */
        geomerative.RG.init(this);
        font = new RFont("Laserfont.ttf", 80, RFont.CENTER);
        
        smooth();
        colorMode(RGB);
        stroke(LaserinneSketch.SCREEN_COLOR);
        noFill();
    }
    
    public void draw() {
        background(0);
        stroke(TwoPlayerCompetition.SCREEN_COLOR);
        
        /*
         * Rotate/skew code in place for adapting to the slope.
         */
        // float cameraZ = (float) ((height/2.0) / Math.tan(PI * 60.0 / 360.0));
        // perspective(PI / 3.0, width/height, cameraZ/10.0, cameraZ*10.0);
        
        float eyeX = width / 2.0f,
              eyeY = height / 2.0f,
              eyeZ = (float) ((height / 2.0) / Math.tan(PI * 60.0 / 360.0)),
              centerX = width / 2.0f,
              centerY = height / 2.0f,
              centerZ = 0,
              upX = 0,
              upY = 1,
              upZ = 0;
        camera(eyeX, eyeY, eyeZ, centerX, centerY, centerZ, upX, upY, upZ);
        
        // rotateX(-PI * 1 / 3);
        
        /*
         * Draw FPS on screen
         */
        pushMatrix();
        translate(30, 80);
        font.setAlign(RFont.LEFT);
        font.draw(new Integer(Math.round(frameRate)).toString());
        popMatrix();
        
        /*
         * Update tracking
         */
        if (tracking != null) tracking.update();
    }
    
    /**
     * Use this method to draw stuff with laser. Class TwoPlayerCompetition has
     * an example on how to use this.
     */
    protected abstract void drawWithLaser();
}
