/**
 * XORShiftRandom
 * 
 * @see http://stackoverflow.com/questions/453479/how-good-is-java-util-random
 * @see http://www.javamex.com/tutorials/random_numbers/xorshift.shtml
 * @see http://www.javamex.com/tutorials/random_numbers/java_util_random_subclassing.shtml
 * @see http://www.jstatsoft.org/v08/i14/paper
 * 
 * @author Jyrki Lilja
 */

package com.laserinne.util;

public class XORShiftRandom extends java.util.Random {
    /**
     * Generated by Jyrki Lilja on 2011-08-09 11.02
     */
    private static final long serialVersionUID = -1653817394936639091L;
    
    private long seed;
    
    public XORShiftRandom() {
        this.setSeed(System.nanoTime());
    }
    
    synchronized public void setSeed(long seed) {
        super.setSeed(seed);
        this.seed = seed;
    }
    
    synchronized protected int next(int nbits) {
        long x = this.seed;
        x ^= (x << 21);
        x ^= (x >>> 35);
        x ^= (x << 4);
        this.seed = x;
        x &= ((1L << nbits) -1);
        return (int) x;
    }
    
    public double nextDouble() {
        double d = super.nextDouble();
        return d;
    }
}